services:

  app:
    image: maven:3.9.8
    working_dir: /app
    networks:
      - auth
    environment:
      - DB_URL=jdbc:mysql://db:3306/zone_clear
      - DB_USERNAME=rabano
      - DB_PASSWORD=htmlcssjs
      - DLL=update
    ports:
      - 8080:8080
    volumes:
      - .:/app
    command: "mvn spring-boot:run"

  db:
    image: mysql
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=rabano
      - MYSQL_PASSWORD=htmlcssjs
      - MYSQL_DATABASE=zone_clear
    ports:
      - 3306:3306
    networks:
      - auth

  pma:
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_HOST=db
      - PMA_USER=rabano
      - PMA_PASSWORD=htmlcssjs
    networks:
      - auth

networks:
  auth:
