spring:
  application:
    name: ZoneClear

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${DLL}
    show-sql: true
    open-in-view: true

  security:
    jwt:
      user-creator: Hola
      private-key: Si